[package]
name = "account"
version = "0.1.0"
edition = "2024"
description = "Account domain library, reusable across projects"
license = "MIT"

[dependencies]
rust_decimal =  { version = "1.43.0", features = ["macros", "serde-with-str"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"