[package]
name = "graydb"
version = "0.1.0"
edition = "2024"
description = "GrayDB application: data access / settlement persistence layer"

[dependencies]
account = { path = "../account" }
rust_decimal =  { version = "1.43.0", features = ["macros", "serde-with-str"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"